flaskapp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskapp/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskapp import db
from flaskapp.models import Post
from flaskapp.posts.forms import PostForm

posts = Blueprint('posts', __name__)

#new post
@posts.route("/posts/new",methods=['GET','POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data,content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash('Your post has been created','success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html',title='New Post',form=form,legend='New Post')

#post
@posts.route("/post/<int:post_id>")
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title=post.title, post=post)


#update post	
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',form=form, legend='Update Post')


#delete post
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Your post has been deleted!', 'success')
	return redirect(url_for('main.home'))

flaskapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskapp import db
from passlib.hash import sha256_crypt
from flaskapp.models import User, Post
from flaskapp.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskapp.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


#register
@users.route('/register',methods =['GET','POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hash_password = sha256_crypt.encrypt(str(form.password.data))
		user = User(name=form.name.data, username=form.username.data, email=form.email.data,password=hash_password)
		db.session.add(user)
		db.session.commit()
		
		flash('You are now registered and can log in', 'success')

		return redirect(url_for('users.login'))

	return render_template('register.html',title='Register',form= form)

#user login
@users.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.users'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and sha256_crypt.verify(form.password.data, user.password):
			login_user(user, remember=form.remember.data)
			flash('You are now logged in', 'success')
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Email or Password are wrong','danger')
			return redirect(url_for('users.login'))

	return render_template('login.html',title='Login',form = form)


#logout
@users.route("/logout")
def logout():
	logout_user()
	flash('You are logged out','info')
	return redirect(url_for('main.home'))

#account
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated', 'success')
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	return render_template('account.html',title='Account',image_file=image_file,form=form)

#users posts
@users.route("/user/<string:username>")
def user_posts(username):
	page = request.args.get('page', 1,type=int)
	user = User.query.filter_by(username=username).first_or_404()
	posts = Post.query.filter_by(author=user)\
	.order_by(Post.date_posted.desc())\
	.paginate(page=page, per_page=6)
	return render_template('user_posts.html',title="Posts",posts=posts,user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html',title='Reset Password',form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hash_password = sha256_crypt.encrypt(str(form.password.data))
		user.password =  hash_password
		db.session.commit()
		flash('Your password has been updated. You can log in', 'success')
		return redirect(url_for('users.login'))

	return render_template('reset_token.html', title='Reset Password', form=form)

flaskapp/templates/about.html
{% extends 'layout.html' %}

{% block body %}
<div class="content-section">
    <h1>About Us</h1>
    <p>This is About Page</p>
</div>
{% endblock %}

flaskapp/templates/account.html
{% extends 'layout.html' %}
{% block body %}
	{% from "includes/_formhelpers.html" import render_field %}
	<div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
       </div>
       <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"><h2>Account Info</h2></legend>
                <div class="form-group">
                    {{render_field(form.username)}}
                </div>
                <div class="form-group">
                    {{render_field(form.email)}}
                </div>
                <div class="form-group">
                    {{ form.picture.label }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                    	{% for error in form.picture.errors %}
                    		<span class="text-danger">{{ error }} </span></br>
                    	{% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
 	</div>
{% endblock %}

flaskapp/templates/create_post.html
{% extends "layout.html" %}
{% block body %}
    {% from "includes/_formhelpers.html" import render_field %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"><h2>{{ legend }} </h2></legend>
                <div class="form-group">
                    {{render_field(form.title)}}
                </div>
                <div class="form-group">
                  {{ form.content.label(class="form-control-label") }}
                  {% if form.content.errors %}
                   {{ form.content(class="form-control form-control-lg is-invalid ",id="editor") }}
                     <div class="alert-danger">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                           {% endfor %}
                           </div>
                   {% else %}
                 {{ form.content(class="form-control form-control-lg",id="editor") }}
                 {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
    
{% endblock %}

flaskapp/templates/home.html
{% extends 'layout.html' %}

{% block body %}
	<div class="row">
    {% for post in posts.items %}
    <div class="col-lg-6 col-md-12">
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts',username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
	<small class="text-muted">Posted {{ moment(post.date_posted).fromNow(refresh=True) }}</small>

            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content | truncate(200) | safe}}</p>
            <h6><a class="article-metadata" href="{{ url_for('posts.post', post_id=post.id) }}">Continue Reading</a></h6>
          </div>
        </article>
    </div>
    {% endfor %}
    </div>


    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
    	{% if page_num %}
    		{% if posts.page ==  page_num %}
    		<a class="btn btn-info mb-4" href="{{ url_for('main.home',page=page_num) }}">{{ page_num }}</a>
    		{% else %}
    		<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home',page=page_num) }}">{{ page_num }}</a>
    		{% endif %}
    	{% else %}
    		...
    	{% endif %}
    {% endfor %}

{% endblock %}

flaskapp/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="ufc-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
      <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
          <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
	{{ moment.include_jquery() }}
	{{ moment.include_moment() }}
  </head>
  {% if title %}
        <title>FlaskApp - {{ title }}</title>
    {% else %}
        <title>FlaskApp</title>
    {% endif %}
  <body>
  	{% include 'includes/_navbar.html' %}
  	<main role="main" class="container">
      {% include 'includes/_messages.html' %}
	
      {% block body %} {% endblock %}
      
      
  </main>
    
  
         <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="//cdn.ckeditor.com/4.11.4/standard/ckeditor.js"></script>
    <script type="text/javascript">
      CKEDITOR.replace('editor')
    </script>

  </body>
</html>
 

flaskapp/templates/login.html
{% extends 'layout.html' %}
{% block body %}
{% from "includes/_formhelpers.html" import render_field %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }} 
                <legend class="border-bottom mb-4"><h2>Login</h2></legend>      
                <div class="form-group">
                    {{render_field(form.email)}}
                </div>
                <div class="form-group">
                    {{render_field(form.password)}}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}

                    {{ form.remember.label(class="form-check-label ") }}
                </div>
    <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
    <small class="text-muted ml-2"><a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
    </small>
    </div>
    
  </form>
  <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
</div>
{% endblock %}

flaskapp/templates/post.html
{% extends "layout.html" %}
{% block body %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts',username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
	<small class="text-muted"> Posted {{ moment(post.date_posted).fromNow(refresh=True) }}</small>
              {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
            </div>
            <h2><a class="article-title">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content | safe}}</p>
          </div>
        </article>
        <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

flaskapp/templates/register.html
{% extends "layout.html" %}
{% block body %}
    {% from "includes/_formhelpers.html" import render_field %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"><h2>Join Today</h2></legend>
                <div class="form-group">
                    {{render_field(form.name)}}
                </div>
                <div class="form-group">
                    {{render_field(form.username)}}
                </div>
                <div class="form-group">
                    {{render_field(form.email)}}
                </div>
                <div class="form-group">
                    {{render_field(form.password)}}
                </div>
                <div class="form-group">
                    {{render_field(form.confirm)}}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock %}

flaskapp/templates/reset_request.html
{% extends 'layout.html' %}
{% block body %}
{% from "includes/_formhelpers.html" import render_field %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }} 
                <legend class="border-bottom mb-4"><h2>Reset Password</h2></legend>      
                <div class="form-group">
                    {{render_field(form.email)}}
                </div>
    <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
        </div>
  </form>
</div>

{% endblock %}

flaskapp/templates/reset_token.html
{% extends 'layout.html' %}
{% block body %}
{% from "includes/_formhelpers.html" import render_field %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }} 
                <legend class="border-bottom mb-4"><h2>Reset Password</h2></legend>      
                <div class="form-group">
                    {{render_field(form.password)}}
                </div>
                <div class="form-group">
                    {{render_field(form.confirm)}}
                </div>
    <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
        </div>
  </form>
</div>

{% endblock %}

flaskapp/templates/user_posts.html
{% extends "layout.html" %}
{% block body %}
  <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
  <div class="row">
    {% for post in posts.items %}
    <div class="col-lg-6 col-md-12">
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts',username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
	<small class="text-muted"> Posted {{ moment(post.date_posted).fromNow(refresh=True) }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content | truncate(200) | safe}}</p>
            <h6><a class="article-metadata" href="{{ url_for('posts.post', post_id=post.id) }}">Continue Reading</a></h6>
          </div>
        </article>
      </div>
    {% endfor %}
  </div>

    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
      {% if page_num %}
        {% if posts.page ==  page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts',username=user.username,page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts',username=user.username,page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock %}