flaskapp/main/routes.py
from flask import render_template, request, Blueprint
from flaskapp.models import Post, User
from flask_login import current_user

main = Blueprint('main', __name__)

#main page
@main.route("/")
def home():
	page = request.args.get('page', 1,type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=6)
	return render_template('home.html',posts=posts)

#about page
@main.route('/about')
def about():
	return render_template('about.html',title='About')

flaskapp/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskapp import db
from flaskapp.models import Post
from flaskapp.posts.forms import PostForm

posts = Blueprint('posts', __name__)

#new post
@posts.route("/posts/new",methods=['GET','POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data,content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash('Your post has been created','success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html',title='New Post',form=form,legend='New Post')

#post
@posts.route("/post/<int:post_id>")
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title=post.title, post=post)


#update post	
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',form=form, legend='Update Post')


#delete post
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Your post has been deleted!', 'success')
	return redirect(url_for('main.home'))

flaskapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskapp import db
from passlib.hash import sha256_crypt
from flaskapp.models import User, Post
from flaskapp.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskapp.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


#register
@users.route('/register',methods =['GET','POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hash_password = sha256_crypt.encrypt(str(form.password.data))
		user = User(name=form.name.data, username=form.username.data, email=form.email.data,password=hash_password)
		db.session.add(user)
		db.session.commit()
		
		flash('You are now registered and can log in', 'success')

		return redirect(url_for('users.login'))

	return render_template('register.html',title='Register',form= form)

#user login
@users.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.users'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and sha256_crypt.verify(form.password.data, user.password):
			login_user(user, remember=form.remember.data)
			flash('You are now logged in', 'success')
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Email or Password are wrong','danger')
			return redirect(url_for('users.login'))

	return render_template('login.html',title='Login',form = form)


#logout
@users.route("/logout")
def logout():
	logout_user()
	flash('You are logged out','info')
	return redirect(url_for('main.home'))

#account
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated', 'success')
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	return render_template('account.html',title='Account',image_file=image_file,form=form)

#users posts
@users.route("/user/<string:username>")
def user_posts(username):
	page = request.args.get('page', 1,type=int)
	user = User.query.filter_by(username=username).first_or_404()
	posts = Post.query.filter_by(author=user)\
	.order_by(Post.date_posted.desc())\
	.paginate(page=page, per_page=6)
	return render_template('user_posts.html',title="Posts",posts=posts,user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html',title='Reset Password',form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hash_password = sha256_crypt.encrypt(str(form.password.data))
		user.password =  hash_password
		db.session.commit()
		flash('Your password has been updated. You can log in', 'success')
		return redirect(url_for('users.login'))

	return render_template('reset_token.html', title='Reset Password', form=form)

flaskapp/templates/includes/_formhelpers.html
{% macro render_field(field) %}
  {{ field.label(class="form-control-label") }}
  {% if field.errors %}
   {{ field(class="form-control form-control-lg is-invalid ") }}
     <div class="alert-danger">
    	{% for error in field.errors %}
            <span>{{ error }}</span>
           {% endfor %}
           </div>
   {% else %}
 {{ field(class="form-control form-control-lg") }}
 {% endif %}
{% endmacro %}

flaskapp/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}

{% if error%}
<div class="alert alert-danger">{{error}}</div>
{% endif%}

{% if msg%}
<div class="alert alert-sucess">{{msg}}</div>
{% endif%}

flaskapp/templates/includes/_navbar.html
<header class="site-header">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask App</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.user_posts',username=current_user.username) }}">My Posts</a>
              {% endif %}
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>         
          </div>      
        </div>
      </nav>
</header>